version: "3.7"

services:
  stream_monitor:
    container_name: StreaMonitor
    build: ./
    image: stream_monitor:latest
    volumes:
      - ./downloads:/app/downloads
      - ./config.json:/app/config.json
      - ./parameters.py:/app/parameters.py
    networks:
      - cloudflared_network
    # ports:
    #   - '6969:6969'

networks:
  cloudflared_network:
    external: true
